Bowls Eye: stepperMotor.h File Reference
stepperMotor.h File Reference
#include <pigpio.h>
#include "globals.h"
Data Structures
struct StepperMotor_t
Functions
void StepperMotor_construct (StepperMotor_t *stepper)
void StepperMotor_enable (StepperMotor_t *stepper)
void StepperMotor_update (StepperMotor_t *stepper)
void StepperMotor_setDirection (StepperMotor_t *stepper, uint8_t direction)
void StepperMotor_setStepSize (StepperMotor_t *stepper, int *multiple)
void StepperMotor_enA (StepperMotor_t *stepper)
void StepperMotor_enB (StepperMotor_t *stepper)
void StepperMotor_disable (StepperMotor_t *stepper)
void StepperMotor_incrementStep (StepperMotor_t *stepper)
void StepperMotor_decrementStep (StepperMotor_t *stepper)
void StepperMotor_wrapStep (StepperMotor_t *stepper)
void StepperMotor_step0 (StepperMotor_t *stepper)
void StepperMotor_step1 (StepperMotor_t *stepper)
void StepperMotor_step2 (StepperMotor_t *stepper)
void StepperMotor_step3 (StepperMotor_t *stepper)
Detailed Description
Author
Harvey Leicester
Definition in file stepperMotor.h.
Function Documentation
void StepperMotor_construct (StepperMotor_t * stepper)
Constructor for StepperMotor_t
Parameters
stepper Instance of StepperMotor_t
multiple Multiple of minimum step angle (0.9deg), defines angular resolution of system
Definition at line 19 of file stepperMotor.c.
References StepperMotor_t::direction, StepperMotor_t::pinB1, StepperMotor_t::pinEnA, StepperMotor_enable(), StepperMotor_step0(), StepperMotor_step1(), StepperMotor_step2(), StepperMotor_step3(), StepperMotor_t::totalSteps, and StepperMotor_t::waitTime.
void StepperMotor_decrementStep (StepperMotor_t * stepper)
Decrement the current step of the motor
Parameters
stepper Instance of StepperMotor_t
Definition at line 163 of file stepperMotor.c.
References StepperMotor_wrapStep(), and StepperMotor_t::totalSteps.
Referenced by StepperMotor_update(), and StepperMotor_wrapStep().
void StepperMotor_disable (StepperMotor_t * stepper)
Disable the stepper motor
Parameters
stepper Instance of StepperMotor_t
Definition at line 117 of file stepperMotor.c.
References StepperMotor_t::pinB1, and StepperMotor_t::pinEnA.
void StepperMotor_enA (StepperMotor_t * stepper)
Enable the A H bridge of the stepper motor driver
Parameters
stepper
Definition at line 132 of file stepperMotor.c.
References StepperMotor_t::pinEnA.
void StepperMotor_enable (StepperMotor_t * stepper)
Enable the stepper motor
Parameters
stepper Instance of StepperMotor_t
Definition at line 102 of file stepperMotor.c.
References StepperMotor_t::pinB1, and StepperMotor_t::pinEnA.
Referenced by StepperMotor_construct().
void StepperMotor_enB (StepperMotor_t * stepper)
Enable the B H bridge of the stepper motor driver
Parameters
stepper
Definition at line 141 of file stepperMotor.c.
void StepperMotor_incrementStep (StepperMotor_t * stepper)
Increment the current step of the motor
Parameters
stepper Instance of StepperMotor_t
Definition at line 150 of file stepperMotor.c.
References StepperMotor_wrapStep(), and StepperMotor_t::totalSteps.
Referenced by StepperMotor_update(), and StepperMotor_wrapStep().
void StepperMotor_setDirection (StepperMotor_t * stepper, uint8_t direction)
Set the rotational direction of the motor
Parameters
stepper Instance of StepperMotor_t
direction Direction to assign
Definition at line 93 of file stepperMotor.c.
References StepperMotor_t::direction.
void StepperMotor_setStepSize (StepperMotor_t * stepper, int * multiple)
Set the size of the motor step increment, defines the angular resolution of the system
Parameters
stepper Instance of StepperMotor_t
multiple Multiple of minimum step increment (0.9deg)
Definition at line 83 of file stepperMotor.c.
void StepperMotor_step0 (StepperMotor_t * stepper)
Method for performing a step
Parameters
stepper Instance of StepperMotor_t
Definition at line 243 of file stepperMotor.c.
References StepperMotor_t::pinB1.
Referenced by StepperMotor_construct().
void StepperMotor_step1 (StepperMotor_t * stepper)
Method for performing a step
Parameters
stepper Instance of StepperMotor_t
Definition at line 231 of file stepperMotor.c.
References StepperMotor_t::pinB1.
Referenced by StepperMotor_construct().
void StepperMotor_step2 (StepperMotor_t * stepper)
Method for performing a step
Parameters
stepper Instance of StepperMotor_t
Definition at line 219 of file stepperMotor.c.
References StepperMotor_t::pinB1.
Referenced by StepperMotor_construct().
void StepperMotor_step3 (StepperMotor_t * stepper)
Method for performing a step
Parameters
stepper Instance of StepperMotor_t
Definition at line 207 of file stepperMotor.c.
References StepperMotor_t::pinB1.
Referenced by StepperMotor_construct().
void StepperMotor_update (StepperMotor_t * stepper)
Update the stepper motor position
Parameters
stepper Instance of StepperMotor_t
Definition at line 54 of file stepperMotor.c.
References StepperMotor_t::direction, StepperMotor_decrementStep(), StepperMotor_incrementStep(), and StepperMotor_t::waitTime.
void StepperMotor_wrapStep (StepperMotor_t * stepper)
Wrap current step of motor at limits
Parameters
stepper Instance of StepperMotor_t
Definition at line 175 of file stepperMotor.c.
References StepperMotor_decrementStep(), StepperMotor_incrementStep(), StepperMotor_t::totalSteps, and StepperMotor_t::waitTime.
Referenced by StepperMotor_decrementStep(), and StepperMotor_incrementStep().