.TH "StepperMotor_t" 3 "Sat Mar 24 2018" "Version 1.0" "Bowls Eye" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StepperMotor_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stepperMotor\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBpinEnA\fP"
.br
.ti -1c
.RI "uint8_t \fBpinB1\fP"
.br
.ti -1c
.RI "int8_t \fBcurrentStep\fP"
.br
.ti -1c
.RI "double \fBwaitTime\fP"
.br
.ti -1c
.RI "uint8_t \fBstepMultiple\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure for interfacing with stepper motor and its dual H bridge driver 
.PP
Definition at line 34 of file stepperMotor\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int8_t StepperMotor_t::currentStep"
Current step of the motor 
.PP
Definition at line 38 of file stepperMotor\&.h\&.
.SS "uint8_t StepperMotor_t::pinB1"
The pins used to enable the coils of the motor 
.PP
Definition at line 37 of file stepperMotor\&.h\&.
.SS "uint8_t StepperMotor_t::pinEnA"
Contains the methods for performing each step< 
.PP
Definition at line 37 of file stepperMotor\&.h\&.
.SS "uint8_t StepperMotor_t::stepMultiple"
Rotational direction and angular resolution 
.PP
Definition at line 40 of file stepperMotor\&.h\&.
.SS "double StepperMotor_t::waitTime"
Time to wait/delay between steps 
.PP
Definition at line 39 of file stepperMotor\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bowls Eye from the source code\&.
