.TH "BluetoothServer_t" 3 "Sat Mar 24 2018" "Version 1.0" "Bowls Eye" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BluetoothServer_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <bluetoothController\&.h>\fP
.SH "Detailed Description"
.PP 
Structure for creating a Bluetooth server 
.PP
Definition at line 22 of file bluetoothController\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bowls Eye from the source code\&.
