.TH "globals.h" 3 "Mon Apr 16 2018" "Version 1.0" "Bowls Eye" \" -*- nroff -*-
.ad l
.nh
.SH NAME
globals.h \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Harvey Leicester 
.RE
.PP

.PP
Definition in file \fBglobals\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bowls Eye from the source code\&.
