.TH "LED_t" 3 "Mon Apr 16 2018" "Version 1.0" "Bowls Eye" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LED_t \- Wrapper for interfacing with LEDs (or other gpio pins)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <led\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBpin\fP"
.br
.ti -1c
.RI "uint8_t \fBstate\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Wrapper for interfacing with LEDs (or other gpio pins) 
.PP
Definition at line 17 of file led\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int LED_t::pin"
pin of LED 
.PP
Definition at line 19 of file led\&.h\&.
.PP
Referenced by LED_construct(), LED_high(), LED_low(), and LED_toggle()\&.
.SS "uint8_t LED_t::state"
state of pin/LED 
.PP
Definition at line 20 of file led\&.h\&.
.PP
Referenced by LED_construct(), LED_high(), LED_low(), and LED_toggle()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bowls Eye from the source code\&.
