.TH "main.c" 3 "Mon Apr 16 2018" "Version 1.0" "Bowls Eye" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <signal\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <pigpio\&.h>\fP
.br
\fC#include 'adc\&.h'\fP
.br
\fC#include 'stepperMotor\&.h'\fP
.br
\fC#include 'thread\&.h'\fP
.br
\fC#include 'transducer\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Bowls Eye from the source code\&.
