Bowls Eye: bluetoothController.h File Reference
bluetoothController.h File Reference
#include <stdio.h>
#include <unistd.h>
#include <sys/socket.h>
#include <bluetooth/bluetooth.h>
#include <bluetooth/rfcomm.h>
Classes
struct BluetoothServer_t
Structure for creating a Bluetooth server.
struct BluetoothClient_t
Structure for creating a Bluetooth client.
Functions
void BluetoothServer_construct (BluetoothServer_t *server)
void BluetoothServer_enable (BluetoothServer_t *server)
void BluetoothServer_disable (BluetoothServer_t *server)
void BluetoothServer_readInt (BluetoothServer_t *server, int *dst)
void BluetoothServer_readChar (BluetoothServer_t *server, char *dst)
void BluetoothClient_construct (BluetoothClient_t *client)
void BluetoothClient_enable (BluetoothClient_t *client)
void BluetoothClient_disable (BluetoothClient_t *client)
void BluetoothClient_sendString (BluetoothClient_t *client, char *data, int size)
void BluetoothClient_checkError (BluetoothClient_t *client)
Detailed Description
Author
Harvey Leicester
Definition in file bluetoothController.h.
Function Documentation
void BluetoothClient_checkError (BluetoothClient_t * client)
Check for errors in status of Bluetooth client
Parameters
client Instance of BluetoothClient_t
Definition at line 147 of file bluetoothController.c.
References BluetoothClient_t::status.
Referenced by BluetoothClient_enable(), and BluetoothClient_sendString().
void BluetoothClient_construct (BluetoothClient_t * client)
constructor for BluetoothClient_t
Parameters
client Instance of BluetoothClient_t
Definition at line 100 of file bluetoothController.c.
References BluetoothClient_t::addr, BluetoothClient_enable(), and BluetoothClient_t::dst.
void BluetoothClient_disable (BluetoothClient_t * client)
Disables a Bluetooth client
Parameters
client Instance of BluetoothClient_t
Definition at line 126 of file bluetoothController.c.
void BluetoothClient_enable (BluetoothClient_t * client)
Enables a Bluetooth client
Parameters
client Instance of BluetoothClient_t
Definition at line 116 of file bluetoothController.c.
References BluetoothClient_t::addr, BluetoothClient_checkError(), and BluetoothClient_t::status.
Referenced by BluetoothClient_construct().
void BluetoothClient_sendString (BluetoothClient_t * client, char * data, int size)
Send a string of data to connected Bluetooth server
Parameters
client Instance of bluetoothClient_t
data Data to send
size Size of data to send
Definition at line 137 of file bluetoothController.c.
References BluetoothClient_checkError(), and BluetoothClient_t::status.
void BluetoothServer_construct (BluetoothServer_t * server)
Constructor for BluetoothServer_t
Parameters
server Instance of BluetoothServer_t
Definition at line 16 of file bluetoothController.c.
References BluetoothServer_enable(), BluetoothServer_t::locAddr, BluetoothServer_t::opt, BluetoothServer_t::recData, and BluetoothServer_t::remAddr.
void BluetoothServer_disable (BluetoothServer_t * server)
Disables Bluetooth server
Parameters
server Instance of BluetoothServer_t
Definition at line 53 of file bluetoothController.c.
References BluetoothServer_t::client.
void BluetoothServer_enable (BluetoothServer_t * server)
Enablea the Bluetooth server
Parameters
server Instance of BluetoothServer_t
Definition at line 39 of file bluetoothController.c.
References BluetoothServer_t::buf, BluetoothServer_t::client, BluetoothServer_t::opt, and BluetoothServer_t::remAddr.
Referenced by BluetoothServer_construct().
void BluetoothServer_readChar (BluetoothServer_t * server, char * dst)
Read character value(s) from a connected Bluetooth client
Parameters
server Instance of BluetoothServer_t
dst Destination of received data
Definition at line 84 of file bluetoothController.c.
References BluetoothServer_t::client, and BluetoothServer_t::recData.
void BluetoothServer_readInt (BluetoothServer_t * server, int * dst)
Read integer value(s) from a connected Bluetooth client
Parameters
server Instance of BluetoothServer_t
dst Destination of received data
Definition at line 64 of file bluetoothController.c.
References BluetoothServer_t::client, and BluetoothServer_t::recData.